//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job()
        {
            this.Emp_Job = new HashSet<Emp_Job>();
        }
    
        public int job_No { get; set; }
        public string job_title { get; set; }
        public string job_description { get; set; }
        public System.DateTime job_date { get; set; }
        public byte[] job_attachement { get; set; }
        public string job_status { get; set; }
        public int client_user_no { get; set; }
    
        public virtual Client_User Client_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emp_Job> Emp_Job { get; set; }
    }
}
