//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int users_no { get; set; }
        public string users_name { get; set; }
        public string users_password { get; set; }
        public string users_level { get; set; }
        public int Emp_no { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
